version: '3.7'

services:
  # Redmine本体
  redmine:
    image: redmine:6.0
    container_name: redmine
    ports:
      - '33000:3000'
    expose:
      - '3000'
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/public/themes:/usr/src/redmine/public/themes
    restart: always
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      TZ: Asia/Tokyo
    depends_on:
      - postgres

  # DBサーバ
  postgres:
    image: postgres:16
    container_name: postgres_redmine
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      POSTGRES_DB: redmine
      TZ: Asia/Tokyo

volumes:
  redmine:
  postgres:
