# zabbix docker-compose.yml
# これはZabbixをPostgreSQLと共にDockerで実行するためのdocker-compose.ymlファイルです
# PostgreSQLのバージョンは15を使用し、Zabbixのバージョンは7.0を使用しています
# この構成では、ZabbixサーバーとWebインターフェースがセットアップされます

version: '3.5'

services:
  # PostgreSQLデータベースのサービス(postgres)を命名します
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - ./zabbix-db:/var/lib/postgresql/data

  # Zabbixサーバーのサービス(zabbix-server)を命名します
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - "10051:10051"

  # Zabbix Webインターフェースのサービス(zabbix-web)を命名します
  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:alpine-7.0-latest
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Tokyo
    ports:
      - "8080:8080"
